### ISSUE TITLE
Slack team participation

### ISSUE THREAD

**Issue by FelixPetriconi** [stlab/adobe_source_libraries#45]
Hi,

could you add me to the ASL's Slack team?
I would like to add Windows support for the ASL and discuss/see, if some one else is already working on this, whom I could support in case?

Thanks and regards, 
Felix

**Comment by ilelann** [comment]
Not really "working on this" but I got something up and running with MinGW some time ago with a patch to ASL https://github.com/ilelann/adobe_source_libraries/commit/faa92632530b7c54e47401a28c8c6407e1e10b54 and APL https://github.com/ilelann/adobe_platform_libraries/commit/c8831cd7398b532955d3a5933a5fc9081b935e05

ASL/APL does not really lacks "Windows support", but ASL requires strong C++11 support and VS2015 still had issues, as far as I can remember.
That's why I attempted MinGW, which hit me for missing std::thread support, at least for the version I picked. Hence the commits above to redirect few things to Boost.

Regards,
Ivan

**Comment by FelixPetriconi** [comment]
Hi Ivan,
 
Sean talked in his C++ PodCast some weeks ago about Property Models and I wanted
to experiment with Adam and Eve. So I cloned this repository and tried to
compile it and run into some issues regarding compiler flags for Windows,
thirdparty source code location, getting the unit test system to run, etc. 
 
So I wanted to bring up some topics on this and ask questions into the group of
ASL maintainers.
 
Thanks and regards,
Felix

**Comment by fosterbrereton** [comment]
Hi @FelixPetriconi - we'd be happy to invite you to the Slack team, can you send me your email address? I'm at adobe.com - fbrereto. Thanks.

**Comment by ilelann** [comment]
I gave a try to VS2015, using my latest cmake commits as base (pull request pending).
(mkdir ..\build && cd ..\build && cmake -DUSE_SYSTEM_BOOST=NO ..\adobe_source_libraries)
I stopped when I saw constexpr-related compile errors triggered by boost/multiprecision/cpp_int/literals.hpp
In case it helps https://github.com/ilelann/adobe_source_libraries/commit/ce73c376a03fd9bbf01e3f3cfc09db633bca26af

**Comment by ilelann** [comment]
Oh by the way, this fresh VS update https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx 
mentions "constexpr improvements". Did not test with that.

**Comment by FelixPetriconi** [comment]
Hi Ivan,
 
I noticed it and I made some experiences. The problem is that certain things now
work, but std::tuple is broken and so other things does not compile any more.
:-(
 
Regards, Felix

**Comment by ilelann** [comment]
I managed to compile ASL with Visual Studio 2015 Update 2. 
It requires minor fixes, I will push a pull request soon. Tests run OK.
I'm also near building APL's begin (with a CMake setup easily derived from the one I created for my GTK backend branch)

Hijack: can we merge https://github.com/stlab/adobe_source_libraries/pull/51 ? Some fixes are common.

**Comment by FelixPetriconi** [comment]
Hi Ivan,

I was working on the same topic. I come across the same problem with std::tuple.
Sean Parent replied to me some weeks ago:

> I’ll have to take a look at the boost::signals2 issue - the removal of
> explicit on any_regular_t was a fairly recent change 
> to allow you to write: any_regular_t x = 42.0; without having to use an
> explicit constructor - I’d rather not add the explicit constructor back in.

So I proposed a patch of boost::signals2 as following:

 template<typename R, typename ... Args>
        class variadic_slot_invoker
      {
      public:
        typedef R result_type;

        template <typename T>
        using remove_cr_t = std::remove_const_t<std::remove_reference_t<T>>;

        variadic_slot_invoker(Args & ... args):
_args(const_cast<remove_cr_t<Args>&>(args)...)
        {}
        template<typename ConnectionBodyType>
          result_type operator ()(const ConnectionBodyType &connectionBody)
const
        {
          return
call_with_tuple_args<result_type>()(connectionBody->slot().slot_function(), 
            _args, mpl::size_t<sizeof...(Args)>());
        }
      private:
        const BOOST_SIGNALS2_TUPLE<remove_cr_t<Args>& ...> _args;
      };

But neither Sean not I had so far time to follow up on this. My recent changes,
for which I did not create to far a PR are here:
https://github.com/FelixPetriconi/adobe_source_libraries/commits/master

Regards, Felix

**Comment by ilelann** [comment]
We definitely had the same issues. And not always the same fixes. I watch your fork :)

About the any/tuple/signal issue, while it's certainly worth to find a fix in boost::signal, I think final behavior results in flaw of all parts involved: 
* boost::any/adobe::any_regular for the implicit one-argument template constructor
* std::tuple for the unrestricted forwarding constructor hiding conversions made below and thus taking priority over copy construction
* boost::signal for ... I don't know what, but it seems you found out :)

Regards,
Ivan
