### ISSUE TITLE
Forest constructor exception safety

### ISSUE THREAD

**Issue by ahmedcharles** [stlab/adobe_source_libraries#49]
The code below does the same test with both forest and list. They should produce the same output, but they don't, because the forest copy constructor does not handle exceptions appropriately.

```
#include "adobe/forest.hpp"

#include <iostream>
#include <list>

bool activate = false;

class test {
public:
  test(int d) : data_(d) { std::cout << "create " << data_ << std::endl; }
  test(const test& o) : data_(o.data_) {
    std::cout << "copy c " << data_ << std::endl;
    if (activate && data_ == 2) {
      std::cout << "throw " << data_ << std::endl;
      throw 0;
    }
  }
  test& operator=(const test& o) {
    data_ = o.data_;
    std::cout << "copy = " << data_ << std::endl;
    return *this;
  }
  ~test() { std::cout << "delete " << data_ << std::endl; }
private:
  friend std::ostream& operator<<(std::ostream& out, const test& o);

  int data_;
};

std::ostream& operator<<(std::ostream& out, const test& o) {
  out << o.data_;
  return out;
}

template<class T>
void x() try {
  using forest = T;

  forest f1;
  f1.push_back(1);
  f1.push_back(2);
  f1.push_back(3);

  activate = true;

  forest f(f1);
} catch(...) { activate = false; }

int main() {
  std::cout << "adobe::forest" << std::endl;
  x<adobe::forest<test>>();
  std::cout << "std::list" << std::endl;
  x<std::list<test>>();
}
```

```
adobe::forest
create 1
copy c 1
delete 1
create 2
copy c 2
delete 2
create 3
copy c 3
delete 3
copy c 1 // never gets deleted below.
copy c 2
throw 2
delete 1
delete 2
delete 3
std::list
create 1
copy c 1
delete 1
create 2
copy c 2
delete 2
create 3
copy c 3
delete 3
copy c 1
copy c 2
throw 2
delete 1
delete 1
delete 2
delete 3
```

**Comment by sean-parent** [comment]
Good catch! Fixed in 77b50c37db78e31b1617aa9ad0643b572951a969

**Comment by ahmedcharles** [comment]
For the record, I just used a delegating constructor, which would probably be simpler than the current solution (just an opinion, though).

**Comment by sean-parent** [comment]
I agree - I just changed it to use a delegating constructor and cleaned up some other items.

**Comment by ahmedcharles** [comment]
One more issue. The change you made to the default constructor `forest() = default;` results in `size_m` being default initialized rather than value initialized, which means it is uninitialized...

**Comment by sean-parent** [comment]
Will look at that. Travis is currently complaining about Eve's use of
forest iterators with an incomplete type. Not certain why my changes broke
that but haven't had time to look deeply.
Sean

**Comment by ahmedcharles** [comment]
I looked at the travis logs and it seems like it's a bug in clang, given that the compiler crashed. I'm using:

Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.4.0
Thread model: posix

And compiling that source file works just fine for me.
