### ISSUE TITLE
Unable to build trunk

### ISSUE THREAD

**Issue by martinbroadhurst** [stlab/adobe_source_libraries#59]
I may well be missing something, but I am unable to build trunk. I am using Ubuntu Server 14.04.1 and clang version 4.0.0. clang++ is working fine.

Here's what I did:

svn co https://github.com/stlab/adobe_source_libraries.git
cd adobe_source_libraries.git/trunk
./configure.sh

This succeeds with:
INFO : You are ready to go!

./build.sh
ERRR : BUILDTOOL unknown. Goodbye.

I add BUILDTOOL=bjam to build.sh

Running ./build.sh now results in clang++ being unable to find any of the standard headers:
E.g.:
../boost_libraries/boost/config/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found

**Comment by ilelann** [comment]
From old and thus doubtful memories, I think I got your last error for some unit tests trying to build in 32bit mode explicitly.
You need to install a 32bit standard library and headers

**Comment by martinbroadhurst** [comment]
I think it's more fundamental than that, as I get the error on the very first file it tries to compile:

INFO : Make sure you run the configure script before this one to ensure dependencies are in place.
INFO : bjam mode unknown. Defaulting to debug.
sysctl: cannot stat /proc/sys/hw/ncpu: No such file or directory
INFO : Found 2 processors.
EXEC : ../boost_libraries/b2 --toolset=clang --without-python --hash -j2 debug
Performing configuration checks

    - 32-bit                   : no  (cached)
    - 64-bit                   : yes (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : yes (cached)
    - symlinks supported       : yes (cached)
    - lockfree boost::atomic_flag : yes (cached)
    - lockfree boost::atomic_flag : yes (cached)
    - lockfree boost::atomic_flag : no  (cached)
...patience...
...patience...
...patience...
...found 5250 targets...
...updating 573 targets...
clang-linux.compile.c++.without-pth /export/Src/adobe_source_libraries.git/built_artifacts/fccaf884b85829048d264073f9341a53/source/zuid_uuid.o
In file included from source/zuid_uuid.cpp:9:
In file included from ./adobe/implementation/zuid_uuid.hpp:12:
In file included from ./adobe/config.hpp:14:
In file included from ../boost_libraries/boost/config.hpp:44:
../boost_libraries/boost/config/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found
#  include <cstddef>
           ^
1 error generated.

  "clang++" -c -x c++ -std=c++11 -fconstexpr-depth=1024 -ftemplate-depth=1024 -stdlib=libc++ -O0 -g -fno-inline -Wall -g -pthread -std=c++11 -fconstexpr-depth=1024 -ftemplate-depth=1024 -stdlib=libc++ -DADOBE_SERIALIZATION -DADOBE_STD_SERIALIZATION -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_NO_CXX11_NUMERIC_LIMITS=1 -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_POSIX -DBOOST_THREAD_USE_LIB -DBOOST_THREAD_USE_LIB=1 -I"." -I".." -I"../boost_libraries" -o "/export/Src/adobe_source_libraries.git/built_artifacts/fccaf884b85829048d264073f9341a53/source/zuid_uuid.o" "source/zuid_uuid.cpp"

...failed clang-linux.compile.c++.without-pth /export/Src/adobe_source_libraries.git/built_artifacts/fccaf884b85829048d264073f9341a53/source/zuid_uuid.o...
^C

**Comment by ilelann** [comment]
Indeed. I see 

-stdlib=libc++ 

 => you have libc++ installed. If not you need to inform clang to use libstdc++

**Comment by martinbroadhurst** [comment]
Ah, that's probably it. Thank you! I shall install libc++ and see if that fixes it.

**Comment by martinbroadhurst** [comment]
It's building splendidly now. Thanks again, Ivan. I'm going to close this issue.
