### ISSUE TITLE
adobe::rotate for forward iterators

### ISSUE THREAD

**Issue by Acu43** [stlab/adobe_source_libraries#61]
adobe::rotate calls overloaded rotate function template best suited for iterator type in hand through tag dispatch.
```cpp 
template <typename I> // I models Forward Iterator
std::pair<I, I> rotate(I f, I m, I l) {
    typedef typename std::iterator_traits<I>::iterator_category iterator_category;
    return rotate(f, m, l, iterator_category());
}
```
In rotate.hpp there is only one other rotate overload which is overloaded for bidirectional iterators.
Where is the std::forward_iterator_tag overload? I couldn't find it in included headers.

**Comment by sean-parent** [comment]
Good catch - there is no forward implementation currently. At the time this was written rotate() did not return the new mid point. That was added with C++11 (it was actually in the original STL but somehow was dropped). I'm not aware of any use for returning both m and m' - this was added in the spirit of "don't throw away potentially useful information" but without a use case I'm inclined to remove rotate from ASL entirely. If you have a compelling use case then I'll look at fixing it.

**Comment by Acu43** [comment]
I was going through ASL and I thought maybe it didn't caught anyone's attention or i'm missing something. 

I can't think of a use case to return both m and m'.  But i can make a pull request if you decide to keep adobe::rotate around.

Thank you for the backround info.
