### ISSUE TITLE
Build Issues for clang toolset for linux and windows

### ISSUE THREAD

**Issue by bhupendra7** [stlab/adobe_source_libraries#64]
The issue occurs when call for build.sh.. I tried to disable std=c++11 but it is not happening
../boost_libraries/boost/config/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found
#  include <cstddef>
           ^~~~~~~~~
1 error generated.

  "clang++" -c -x c++ -std=c++11 -fconstexpr-depth=1024 -ftemplate-depth=1024 -stdlib=libc++ -std=c++14 -O0 -g -fno-inline -Wall -g -pthread -std=c++11 -fconstexpr-depth=1024 -ftemplate-depth=1024 -stdlib=libc++ -std=c++14 -DADOBE_SERIALIZATION -DADOBE_STD_SERIALIZATION -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_NO_CXX11_NUMERIC_LIMITS=1 -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_POSIX -DBOOST_THREAD_USE_LIB -DBOOST_THREAD_USE_LIB=1 -I"." -I".." -I"../boost_libraries" -o "/home/nathbh/adobe/built_artifacts/fccaf884b85829048d264073f9341a53/source/string_pool.o" "source/string_pool.cpp"

**Comment by sean-parent** [comment]
Can you get a simple file to compile with your setup?
```
#include <cstddef>
int main() { }
```
cstddef is a standard file and should be available in the system include path.

**Comment by camio** [comment]
I verified that a build with clang works using the following command line

```
CC=clang CXX=clang++ \
cmake -GNinja \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE \
        -DBUILD_TESTING=ON \
        -DCMAKE_CXX_STANDARD=23 \
        /home/dsankel/code/adobe_source_libraries/
```

This is using clang 14.0 on Ubuntu 22.04. Feel free to reopen if this is still an issue.
